# Generated by Django 4.2.11 on 2024-03-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper',
            new_name='Topics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paper',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qtopics', to='test_app.topics'),
            preserve_default=False,
        ),
    ]
