# Generated by Django 4.2.11 on 2024-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_paper_topics_remove_question_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_correct',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usersolution',
            name='solution',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
    ]
