# Generated by Django 4.2.11 on 2024-03-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_question_option_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='slug',
            field=models.SlugField(default=23),
            preserve_default=False,
        ),
    ]
