# Generated by Django 4.2.11 on 2024-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_topics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
