# Generated by Django 4.2.11 on 2024-03-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_question_option_a_alter_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=22, max_length=6),
            preserve_default=False,
        ),
    ]
