# Generated by Django 4.2.11 on 2024-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
