# Generated by Django 4.2.11 on 2024-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_testuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
