# Generated by Django 4.2.11 on 2024-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_alter_testuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quesid',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
