# Generated by Django 4.2.11 on 2024-03-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_question_quesid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesid',
            new_name='quesno',
        ),
    ]
